#!/usr/bin/node

var name  = process.argv[1].replace(/.*\/(.*)/, '$1');
var nargv = process.argv.length;
if (nargv < 3 || process.argv[2] === "--help") {
  console.error("usage: %s N [FILE]...", name);
  process.exit(2);
}

var count  = parseInt(process.argv[2], 10);
var chunks = [];
process.stdin.on('data', function(chunk) {
  chunks.push(chunk)
});
process.stdin.on('end', function() {
  var src = chunks.join('').replace(/\n$/, '');
  if (count < 0) {
    for (;;) {
      console.log("%s", src);
    }
  } else {
    for (var i = 0; i < count; i++) {
      console.log("%s", src);
    }
  }
});
