#!/usr/bin/python3

import fileinput
from optparse import OptionParser

def main():
    usage='Usage: %prog [OPTION]... [FILE]...'
    version='0.2.0'
    parser = OptionParser(usage=usage, version=version)
    parser.add_option("-d", "--delimiter", dest="string",
                      help="delimit lines by delimiter")

    (options, args) = parser.parse_args()

    delimiter = options.string or ''
    for line in fileinput.input(args):
        line = line.strip()
        if delimiter == '':
            print(''.join(list(reversed(line))))
        else:
            print(delimiter.join(reversed(line.split(delimiter))))

if __name__ == "__main__":
    main()
