#!/usr/bin/perl
use strict;
use warnings;
use utf8;
use File::Basename;

my $name = basename $0;

if (@ARGV < 1 || $ARGV[0] eq '--help') {
  print STDERR "usage: $name N [FILE]...\n";
  exit 2;
}
my $n = $ARGV[0];

shift @ARGV;
my @src = <>;
if ($n < 0) {
  print @src while 1;
} else {
  print @src for 1 .. $n;
}
